name: Code
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Copy deps
        run: >
          mkdir _includes;
          cd _includes;
          curl -OL https://github.com/allejo/jekyll-anchor-headings/raw/master/_includes/anchor_headings.html
      - name: Deploy code
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          enable_jekyll: true
      - name: Checkout posts
        uses: actions/checkout@v2
        with:
          ref: 'posts'
          clean: false
      - name: Deploy posts
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: _posts
          enable_jekyll: true
